[build]
packages = [
    "pyroll"
]

[version]
path = "pyroll/report/__init__.py"

[envs.default]
path = ".venv"
dependencies = [
    "pyroll-core @ {root:uri}/pyroll_core-2.0.3-py3-none-any.whl",
    "pytest ~= 7.0",
    "pyroll-cli ~= 2.0",
]

[envs.test]
path = ""
dependencies = [
    "pytest ~= 7.0",
]

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]

[envs.test.scripts]
all = "pytest tests"
solve = "pytest tests/test_solve.py"